name: egorka
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  rounded_loading_button: ^2.0.8
  geolocator: ^9.0.2
  sliding_up_panel: ^2.0.0+1
  permission_handler: ^10.1.0
  geocoder2: ^1.4.0
  flutter_polyline_points: ^1.0.0
  scale_button: ^2.1.2
  popover: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
